name: Docker CI

on:
  push:
    branches: [ master, main, dev ]
    tags: [ 'v*.*.*' ]
  pull_request: 
    branches: [ master, main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: false
        tags: mood-logger-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: false
        tags: mood-logger-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VITE_API_URL=http://localhost:8000 